# Generated by Django 6.1 on 2026-09-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='category',
            field=models.CharField(choices=[('language', 'Programming Language'), ('tools', 'Tools'), ('soft', 'Soft Skills')], max_length=20),
        ),
    ]
