# Generated by Django 6.1 on 2026-09-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skills_icon_alter_skills_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='icon',
        ),
    ]
