# Generated by Django 6.1 on 2026-09-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='proficiency',
            field=models.IntegerField(default=50),
        ),
    ]
