# Generated by Django 6.1 on 2026-09-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_experience_starred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='starred_by',
        ),
    ]
